language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

before_script: sudo apt-get install pychecker pylint pep8

install:
  - pip install pybuilder --use-mirrors
  - pip install coveralls
  - pyb --debug install_dependencies
script: "pyb --debug -v verify && coverage run --source=src/main/python/fysom pyb run_unit_tests"
after_success:
  - coveralls --verbose
