language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "pypy"
install:
  - pip install pybuilder --use-mirrors
  - pyb --debug install_dependencies
script: "PYTHONPATH=src/main/python pyb --debug -v"

